version: '3.4'

services:
  # Mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - "27017:27017"
  # Tipping bot
  badlabdiscordtipbot:
    container_name: bad-lab-discord-tip-bot
    image: badlabdiscordtipbot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
